<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\QLNhaThuoc.DTO\QLNhaThuoc.DTO.csproj" />
    <ProjectReference Include="..\QLNhaThuoc.DAL\QLNhaThuoc.DAL.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

</Project>
